apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
  labels:
    app: n8n
    version: latest
    component: workflow-engine
spec:
  replicas: 1
  strategy:
    type: Recreate  # Required for single-instance apps with persistent storage
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
        version: latest
    spec:
      containers:
      - name: n8n
        image: n8nio/n8n:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5678
          name: http
          protocol: TCP
        env:
        - name: N8N_HOST
          value: "n8n.yourdomain.com"  # Replace with your domain
        - name: WEBHOOK_URL
          value: "https://n8n.yourdomain.com"  # Replace with your domain
        - name: GENERIC_TIMEZONE
          value: "America/Chicago"
        - name: N8N_METRICS
          value: "true"
        - name: N8N_LOG_LEVEL
          value: "info"
        - name: EXECUTIONS_PROCESS
          value: "main"
        - name: EXECUTIONS_MODE
          value: "queue"
        - name: DB_TYPE
          value: "sqlite"
        - name: N8N_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: n8n-secrets
              key: encryption-key
              optional: true
        volumeMounts:
        - name: n8n-data
          mountPath: /home/node/.n8n
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "8Gi"
            cpu: "4000m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5678
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5678
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
      volumes:
      - name: n8n-data
        persistentVolumeClaim:
          claimName: n8n-data
      securityContext:
        fsGroup: 1000
      restartPolicy: Always
