apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: n8n

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml

images:
  - name: n8nio/n8n
    newTag: latest # {"$imagepolicy": "flux-system:n8n"}
