apiVersion: v1
kind: Service
metadata:
  name: n8n-service
  namespace: n8n
  labels:
    app: n8n
    component: service
spec:
  type: NodePort
  selector:
    app: n8n
  ports:
  - port: 80
    targetPort: 5678
    nodePort: 30080
    protocol: TCP
    name: http
  sessionAffinity: None
